const MOBILE_WIDTH = 600;
const TABLET_WIDTH = 850;
const DESKTOP_WIDTH = 1100;




const lots = [
  {
    id: 806270,
    caption: "104_1",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 30,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 806237,
    caption: "104_2",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 806185,
    caption: "104_3",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 4,
    caption: "104_4",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 5,
    caption: "104_5",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 6,
    caption: "104_6",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 7,
    caption: "104_7",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 8,
    caption: "104_8",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 9,
    caption: "104_9",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 10,
    caption: "104_10",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 11,
    caption: "104_11",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 12,
    caption: "104_12",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 13,
    caption: "104_13",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 14,
    caption: "104_14",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 15,
    caption: "104_15",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 16,
    caption: "104_16",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 17,
    caption: "104_17",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 18,
    caption: "104_18",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 19,
    caption: "104_19",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },

  {
    id: 20,
    caption: "104_20",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 21,
    caption: "104_21",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 22,
    caption: "104_22",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 23,
    caption: "10_23",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 24,
    caption: "10_24",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 25,
    caption: "10_25",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 26,
    caption: "10_26",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 27,
    caption: "10_27",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 28,
    caption: "10_28",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 29,
    caption: "10_29",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },

  //
  {
    id: 30,
    caption: "10_30",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 30,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 31,
    caption: "10_31",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 32,
    caption: "10_32",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 33,
    caption: "10_33",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 34,
    caption: "10_34",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 35,
    caption: "10_35",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 36,
    caption: "10_36",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 37,
    caption: "10_37",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 38,
    caption: "10_38",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 39,
    caption: "10_39",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 40,
    caption: "10_40",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 41,
    caption: "10_41",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 42,
    caption: "10_42",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 43,
    caption: "10_43",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 44,
    caption: "10_44",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 45,
    caption: "10_45",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 46,
    caption: "10_46",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 47,
    caption: "10_47",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 48,
    caption: "10_48",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },

  {
    id: 49,
    caption: "10_49",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 50,
    caption: "10_50",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 51,
    caption: "10_51",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 52,
    caption: "10_52",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 53,
    caption: "110_53",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 54,
    caption: "110_54",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 55,
    caption: "110_55",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 56,
    caption: "111_56",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 57,
    caption: "10_57",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 30,
    weight_count_value: 0,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
  {
    id: 58,
    caption: "10_59",
    caption_short: "Н1 пакеты",
    numbofpackages_value: 0,
    weight_count_value: 10,
    numbofpackages_plan_value: 30,
    net_value: 2999,
    net_plan_value: 11000,
  },
];

const packs = [
  {
    id: 1,
    caption: "1",
    net_value: 2999,
    gross_value: 3000,
    num_package: 1,
    editdate: "16-JUL-21 16:29:50",
    edituser: "KRY_NN",
    numbofpackages_plan: 10,
    weight_plan: 4000,
  },
  {
    id: 2,
    caption: "2",
    net_value: 0,
    gross_value: 0,
    num_package: 2,
    editdate: "17-JUL-21 16:29:50",
    edituser: "KRY_NN",
    numbofpackages_plan: 12,
    weight_plan: 400,
  },

  {
    id: 3,
    caption: "3",
    net_value: '',
    gross_value: '',
    editdate: "16-JUL-21 16:29:50",
    edituser: "KRY_NN",
    numbofpackages_plan: 23,
    weight_plan: 599,
  },


  {
    id: 4,
    caption: "4",
    net_value: '',
    gross_value: '',
    editdate: "16-JUL-21 16:29:50",
    edituser: "KRY_NN",
    numbofpackages_plan: 10,
    weight_plan: 4000,
  },
  {
    id: 5,
    caption: "5",
    net_value: 2999,
  },
  {
    id: 6,
    caption: "6",
    net_value: 1554,
  },
  {
    id: 7,
    caption: "7",
    net_value: 1855,
  },
  {
    id: 8,
    caption: "8",
    net_value: 3655,
  },
  {
    id: 9,
    caption: "9",
    net_value: 0,
  },
];

export { MOBILE_WIDTH, TABLET_WIDTH, DESKTOP_WIDTH, lots, packs };
